runtime: python
service: video-streaming
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 60000
threadsafe: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cpu_utilization:
    target_utilization: 0.75

runtime_config:
  python_version: 2